export const MARVEL_UI_LEXICON = {
  'Navigation Panel': 'S.H.I.E.L.D. Command Deck',
  'Mission Control': 'Avengers Ops Bridge',
  'Track progress blurb': 'Track saga progress, switch modes, and launch your next timeline mission.',
  'Marvel Fan': 'Stark Initiative Agent',
  'Dark': 'Night Ops',
  'Light': 'Day Ops',
  'Theme & Language': 'Protocol Identity',
  'Universe Language': 'Marvel Language',
  'View & Navigate': 'Tactical Routing',
  'Open Settings': 'Open Protocols',
  'Universe Style': 'Timeline Style',
  'Watchlist Mode': 'Mission Priority',
  'Calendar View': 'Multiverse Calendar',
  'List View': 'Mission List',
  'Analytics': 'Jarvis Analytics',
  'Preferences': 'Protocol Settings',
  'Spoiler Safe': 'Spoiler Shield',
  'Performance Mode': 'Arc Reactor Boost',
  'Interface Behavior': 'Helicarrier Behavior',
  'Auto-hide Completed': 'Auto-hide Cleared',
  'Reduce Motion': 'Stabilize Motion',
  'Backup & Restore': 'Stark Backup Vault',
  'S.H.I.E.L.D. Intel Search': 'F.R.I.D.A.Y. Intel Search',
  'Locate any Marvel story node': 'Locate any Marvel timeline node',
  'Back to Home': 'Return to Helicarrier',
  'Back to Home Carousel': 'Return to Helicarrier Deck',
  'Type to begin searching': 'Type to scan the multiverse',
  'Clear Search': 'Clear Scan',
};

export const DC_UI_LEXICON = {
  'Navigation Panel': 'Justice Command Deck',
  'Mission Control': 'Watchtower Mission Hub',
  'Track progress blurb': 'Track chapter progress, switch modes, and guide your next heroic arc.',
  'Marvel Fan': 'Justice League Operative',
  'Dark': 'Knight Mode',
  'Light': 'Daylight Mode',
  'Theme & Language': 'Identity Matrix',
  'Universe Language': 'DC Language',
  'View & Navigate': 'Heroic Routing',
  'Open Settings': 'Open Systems',
  'Universe Style': 'Cinematic Style',
  'Watchlist Mode': 'Arc Priority',
  'Calendar View': 'Crisis Calendar',
  'List View': 'Hero Roster',
  'Analytics': 'Batcomputer Analytics',
  'Preferences': 'Watchtower Preferences',
  'Spoiler Safe': 'Spoiler Cloak',
  'Performance Mode': 'Speed Force Boost',
  'Interface Behavior': 'Watchtower Behavior',
  'Auto-hide Completed': 'Auto-hide Cleared',
  'Reduce Motion': 'Steady Motion',
  'Backup & Restore': 'Fortress Backup Vault',
  'S.H.I.E.L.D. Intel Search': 'Oracle Intel Search',
  'Locate any Marvel story node': 'Locate any DC story node',
  'Back to Home': 'Return to Watchtower',
  'Back to Home Carousel': 'Return to Watchtower Deck',
  'Type to begin searching': 'Type to scan the multiverse',
  'Clear Search': 'Clear Scan',
};

export const LIST_MODES = [
  { id: 'core', label: 'MCU', sublabel: 'Curated List', color: '#c0392b', desc: '60 curated films & series' },
  { id: 'extended', label: 'Extended', sublabel: 'Full Chronological', color: '#4a9ede', desc: 'All entries incl. Netflix, SHIELD & more' },
];
