export const MARVEL_UI_LEXICON = {
  'Navigation Panel': 'Spectrum Rail',
  'Mission Control': 'Marvel Spectrum',
  'Track progress blurb': 'Track your cinematic journey, switch viewing styles, and continue the next story node.',
  'Marvel Fan': 'Spectrum Viewer',
  'Dark': 'Dark',
  'Light': 'Light',
  'Theme & Language': 'Spectrum Studio',
  'Universe Language': 'Universe Tone',
  'View & Navigate': 'Viewing Style',
  'Open Settings': 'Open Spectrum Studio',
  'Universe Style': 'Theme Palette',
  'Watchlist Mode': 'Viewing Path',
  'Calendar View': 'Timeline Canvas',
  'List View': 'Compact List',
  'Analytics': 'Watch Progress',
  'Preferences': 'Settings',
  'Spoiler Safe': 'Spoiler Safe',
  'Performance Mode': 'Poster Data Saver',
  'Interface Behavior': 'Accessibility',
  'Auto-hide Completed': 'Auto-hide Completed',
  'Reduce Motion': 'Reduce Motion',
  'Backup & Restore': 'Data and Backup',
  'S.H.I.E.L.D. Intel Search': 'Spectrum Search',
  'Locate any Marvel story node': 'Find any title, path, phase, or stinger',
  'Back to Home': 'Back to Home',
  'Back to Home Carousel': 'Back to Dashboard',
  'Type to begin searching': 'Type to search the spectrum',
  'Clear Search': 'Clear Search',
};
export const DC_UI_LEXICON = { ...MARVEL_UI_LEXICON, 'Marvel Fan': 'Spectrum Viewer', 'Locate any Marvel story node': 'Find any DC title, path, era, or arc' };
export const LIST_MODES = [
  { id: 'core', label: 'Essential', sublabel: 'Focused Path', color: '#ff375f', desc: 'Curated films and series' },
  { id: 'extended', label: 'Complete', sublabel: 'Full Timeline', color: '#38bdf8', desc: 'Every tracked entry and universe branch' },
];
